export const importPageBuilderTypes = [
  { type: 'contactUs' },
  { type: 'hero' },
  { type: 'cta' },
  { type: 'story' },
  { type: 'features' },
  { type: 'timeline' },
  { type: 'gallery' },
  { type: 'rsvp' },
  { type: 'quote' },
  { type: 'dresscode' },
  { type: 'blog' },
  { type: 'couple' },
  { type: 'journey' },
  { type: 'bridesmaidsGroomsmen' },
  { type: 'wishes' },
  { type: 'locationVenue' },
  { type: 'gift' },
]
